"""add name column to piggybanks

Revision ID: adc82a141218
Revises: 6e80004221fe
Create Date: 2025-06-01 15:34:49.717457

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'adc82a141218'
down_revision: Union[str, None] = '6e80004221fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('piggybanks', sa.Column('name', sa.String(), nullable=False))
    op.drop_column('piggybanks', 'nome')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('piggybanks', sa.Column('nome', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('piggybanks', 'name')
    # ### end Alembic commands ###
